apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: hello-devops
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/deepakjaiswal09/argocd_handson.git
    targetRevision: main
    path: app

    helm:
      releaseName: hello-devops

  destination:
    server: https://kubernetes.default.svc
    namespace: hello-devops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true